export enum LoanMovementType {
    PRINCIPAL_PAYMENT = "ABONO_CAPITAL",
    INTEREST_PAYMENT = "ABONO_INTERES",
    QUOTA_PAYMENT = "PAGO_CUOTA",
    TOTAL_PAYMENT = "PAGO_TOTAL",
    ADDITIONAL_DISBURSEMENT = "DESEMBOLSO_ADICIONAL"
}
